#!/bin/bash -u
#
# Perform a dist upgrade
#

here=$(dirname "$(readlink -f "${0}")")
. "${here}"/lib.sh

cmds=(
	"sudo bash -c '"
	"apt-get -y update &&"
	"apt-get -y -o Dpkg::Options::='--force-confdef' dist-upgrade &&"
	"reboot"
	"' 2>&1 | sudo tee /dev/console"
)

run_parallel -- run "${cmds[*]}"
