#!/bin/bash -eu
#
# Upload and install Debian package(s)
#

. ./lib.sh

locals=()
remotes=()
for f in "${@}" ; do
	if ! [ -f "${f}" ] ; then
		echo "No such file: ${f}" >&2
		exit 1
	fi
	locals+=("${f}")
	remotes+=("/tmp/${f##*/}")
done

do_run_parallel \
	target-pi-cli "${ARGS[@]}" "${RPI_MASTER}" {} put "${SUB_ARGS[@]}" "${locals[@]}" /tmp \; \
	target-pi-cli "${ARGS[@]}" "${RPI_MASTER}" {} run "${SUB_ARGS[@]}" "sudo apt-get --yes update && sudo dpkg -i ${remotes[*]}"
