#!/bin/bash -u
#
# Upload and install packages
#

# Remove the files from the commandline arguments
files=()
args=()
while [ ${#} -gt 0 ] ; do
	if [ -e "${1}" ]  ; then
		files+=("${1}")
	else
		args+=("${1}")
	fi
	shift
done
set -- "${args[@]}"

if [ ${#files[@]} -eq 0 ] ; then
	echo "No Debian packages to install" >&2
	exit 2
fi

. ./lib.sh

tmpd=$(mktemp -d -u)

run_parallel -- run "mkdir ${tmpd}"
run_parallel -- put "${files[@]}" "${tmpd}"
run_parallel -- run "sudo dpkg -i ${tmpd}/* | sudo tee /dev/console"
run_parallel -- run "rm -rf ${tmpd}"
