#!/bin/bash -eu
#
# Install package(s)
#

cmds=(
	"sudo bash -c '"
	"apt-add-repository --yes --no-update --pocket proposed &&"
	"apt-add-repository --yes --no-update --ppa ppa:canonical-kernel-team/bootstrap &&"
	"apt-add-repository --yes --no-update --ppa ppa:canonical-kernel-team/unstable &&"
	"apt-get --yes update &&"
	"apt-get --yes install linux-raspi-unstable"
	"' 2>&1 | sudo tee /dev/console"
)

here=$(dirname "$(readlink -f "${0}")")
. "${here}"/lib.sh

run_parallel -- run "${cmds[*]}"
