#!/bin/bash -eu
#
# Upload and install Debian package(s)
#

locals=()
remotes=()
for f in "${@}" ; do
	if ! [ -f "${f}" ] ; then
		echo "No such file: ${f}" >&2
		exit 1
	fi
	locals+=("${f}")
	remotes+=("/tmp/${f##*/}")
done

cat | ./run-parallel \
		  target-pi-cli "${RPI_MASTER}" {} put "${locals[@]}" /tmp \; \
		  target-pi-cli "${RPI_MASTER}" {} run "sudo apt-get --yes update && sudo dpkg -i ${remotes[*]}"
