#!/bin/bash -u
#
# Run the raspi-rt tests
#

. ./lib.sh

cmds=(
	"bash -c '"
	"rm -rf raspi-rt &&"
	"git config --global http.sslverify false &&"
	"git clone https://git.launchpad.net/~juergh/+git/raspi-rt &&"
	"cd raspi-rt &&"
	"sudo ./install-deps &&"
	"./run-all-tests"
	"' 2>&1 | sudo tee /dev/console"
)

run_parallel -- run "${cmds[*]}"
