#!/bin/bash -eu
#
# Run the raspi-rt tests
#

. ./env.sh
cat | ./run-parallel \
		  target-pi-cli "${RPI_MASTER}" {} \
		  run "rm -rf raspi-rt && git clone https://git.launchpad.net/~juergh/+git/raspi-rt && cd raspi-rt && ./tests/*"
