#!/bin/bash -u
#
# Run the raspi-rt tests
#

. ./lib.sh

cmds=(
	"rm -rf raspi-rt &&"
	"git clone https://git.launchpad.net/~juergh/+git/raspi-rt &&"
	"cd raspi-rt &&"
	"sudo ./install-deps &&"
	"./run-all-tests"
)

run_parallel run "${cmds[*]}"
