#!/bin/bash -eu
#
# Show system state
#

. ./lib.sh

do_run_parallel target-pi-cli "${ARGS[@]}" "${RPI_MASTER}" {} state "${SUB_ARGS[@]}"

echo
echo "-- System states:"
for host in "${HOSTS[@]}" ; do
	state=$(tail -2 "${host}".log | head -1)
	printf "%-25s: %s\n" "${host}" "${state}"
done
