#!/bin/bash -u
#
# Show system state
#

. ./lib.sh

run_parallel state

echo "-- System states:"
for host in "${HOSTS[@]}" ; do
	state=$(tail -2 "${host}".log | head -1)
	printf "%-25s: %s\n" "${host}" "${state}"
done
