#!/bin/bash -u
#
# Show boot time
#

. ./lib.sh

run_parallel run "sudo dmesg"

echo "-- Boot times:"
for host in "${HOSTS[@]}" ; do
	link_ready=$(grep 'eth0: link becomes ready' "${host}".log | \
					 sed -e 's/.*\[\s\s*//' -e 's/\].*//')
	printf "%-25s: %s\n" "${host}" "${link_ready}"
done
