#!/bin/bash -eu
#
# Connect to the serial consoles
#

here=$(dirname "$(readlink -f "${0}")")
. "${here}"/lib.sh
				 
i=0
for r in $(seq 0 2) ; do
	for c in $(seq 0 3) ; do
		x=$((c * 820))
		y=$((r * 570))
		host=${HOSTS[${i}]}
		gnome-terminal --geometry "80x24+${x}+${y}" --title "${host}" -- \
					   console -M ozzy -p 3109 -U "${host}"

		i=$((i + 1))
		if [ ${i} -eq ${#HOSTS[@]} ] ; then
			exit
		fi
	done
done
