#!/bin/bash -u
#
# Show system state
#

here=$(dirname "$(readlink -f "${0}")")
. "${here}"/lib.sh

run_parallel -- state

echo "-- System states:"
for host in "${HOSTS[@]}" ; do
	state=$(tail -2 "${host}".log | head -1)
	printf "%-25s: %s\n" "${host}" "${state}"
done
