#!/bin/bash -u
#
# Show kernel information
#

. ./lib.sh

run_parallel info

echo "-- Kernel versions:"
for host in "${HOSTS[@]}" ; do
	kernel=$(awk '$1 == "\"Kernel\":" { print $4 " " $5 " " $14}' \
				 "${host}".log)
	printf "%-25s: %s\n" "${host}" "${kernel}"
done
