#!/bin/bash -u
#
# Show kernel information
#

here=$(dirname "$(readlink -f "${0}")")
. "${here}"/lib.sh

run_parallel -- info

echo "-- Kernel versions:"
for host in "${HOSTS[@]}" ; do
	kernel=$(awk '$1 == "\"Kernel\":" { print $4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14 }' \
				 "${LOG_DIR}"/"${host}".log)
	printf "%-25s: %s\n" "${host}" "${kernel}"
done
